/*
Pipedrive API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DeleteActivityResponse200 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteActivityResponse200{}

// DeleteActivityResponse200 struct for DeleteActivityResponse200
type DeleteActivityResponse200 struct {
	Success *bool `json:"success,omitempty"`
	Data *DeleteActivityResponse200Data `json:"data,omitempty"`
}

// NewDeleteActivityResponse200 instantiates a new DeleteActivityResponse200 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteActivityResponse200() *DeleteActivityResponse200 {
	this := DeleteActivityResponse200{}
	return &this
}

// NewDeleteActivityResponse200WithDefaults instantiates a new DeleteActivityResponse200 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteActivityResponse200WithDefaults() *DeleteActivityResponse200 {
	this := DeleteActivityResponse200{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *DeleteActivityResponse200) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteActivityResponse200) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *DeleteActivityResponse200) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *DeleteActivityResponse200) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *DeleteActivityResponse200) GetData() DeleteActivityResponse200Data {
	if o == nil || IsNil(o.Data) {
		var ret DeleteActivityResponse200Data
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteActivityResponse200) GetDataOk() (*DeleteActivityResponse200Data, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *DeleteActivityResponse200) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given DeleteActivityResponse200Data and assigns it to the Data field.
func (o *DeleteActivityResponse200) SetData(v DeleteActivityResponse200Data) {
	o.Data = &v
}

func (o DeleteActivityResponse200) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteActivityResponse200) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableDeleteActivityResponse200 struct {
	value *DeleteActivityResponse200
	isSet bool
}

func (v NullableDeleteActivityResponse200) Get() *DeleteActivityResponse200 {
	return v.value
}

func (v *NullableDeleteActivityResponse200) Set(val *DeleteActivityResponse200) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteActivityResponse200) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteActivityResponse200) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteActivityResponse200(val *DeleteActivityResponse200) *NullableDeleteActivityResponse200 {
	return &NullableDeleteActivityResponse200{value: val, isSet: true}
}

func (v NullableDeleteActivityResponse200) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteActivityResponse200) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


