/*
Pipedrive API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetActivityResponse200 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetActivityResponse200{}

// GetActivityResponse200 struct for GetActivityResponse200
type GetActivityResponse200 struct {
	Success *bool `json:"success,omitempty"`
	Data *ActivityResponseObject `json:"data,omitempty"`
	RelatedObjects *GetActivitiesResponse200RelatedObjects `json:"related_objects,omitempty"`
}

// NewGetActivityResponse200 instantiates a new GetActivityResponse200 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetActivityResponse200() *GetActivityResponse200 {
	this := GetActivityResponse200{}
	return &this
}

// NewGetActivityResponse200WithDefaults instantiates a new GetActivityResponse200 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetActivityResponse200WithDefaults() *GetActivityResponse200 {
	this := GetActivityResponse200{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetActivityResponse200) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetActivityResponse200) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetActivityResponse200) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GetActivityResponse200) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetActivityResponse200) GetData() ActivityResponseObject {
	if o == nil || IsNil(o.Data) {
		var ret ActivityResponseObject
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetActivityResponse200) GetDataOk() (*ActivityResponseObject, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetActivityResponse200) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ActivityResponseObject and assigns it to the Data field.
func (o *GetActivityResponse200) SetData(v ActivityResponseObject) {
	o.Data = &v
}

// GetRelatedObjects returns the RelatedObjects field value if set, zero value otherwise.
func (o *GetActivityResponse200) GetRelatedObjects() GetActivitiesResponse200RelatedObjects {
	if o == nil || IsNil(o.RelatedObjects) {
		var ret GetActivitiesResponse200RelatedObjects
		return ret
	}
	return *o.RelatedObjects
}

// GetRelatedObjectsOk returns a tuple with the RelatedObjects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetActivityResponse200) GetRelatedObjectsOk() (*GetActivitiesResponse200RelatedObjects, bool) {
	if o == nil || IsNil(o.RelatedObjects) {
		return nil, false
	}
	return o.RelatedObjects, true
}

// HasRelatedObjects returns a boolean if a field has been set.
func (o *GetActivityResponse200) HasRelatedObjects() bool {
	if o != nil && !IsNil(o.RelatedObjects) {
		return true
	}

	return false
}

// SetRelatedObjects gets a reference to the given GetActivitiesResponse200RelatedObjects and assigns it to the RelatedObjects field.
func (o *GetActivityResponse200) SetRelatedObjects(v GetActivitiesResponse200RelatedObjects) {
	o.RelatedObjects = &v
}

func (o GetActivityResponse200) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetActivityResponse200) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.RelatedObjects) {
		toSerialize["related_objects"] = o.RelatedObjects
	}
	return toSerialize, nil
}

type NullableGetActivityResponse200 struct {
	value *GetActivityResponse200
	isSet bool
}

func (v NullableGetActivityResponse200) Get() *GetActivityResponse200 {
	return v.value
}

func (v *NullableGetActivityResponse200) Set(val *GetActivityResponse200) {
	v.value = val
	v.isSet = true
}

func (v NullableGetActivityResponse200) IsSet() bool {
	return v.isSet
}

func (v *NullableGetActivityResponse200) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetActivityResponse200(val *GetActivityResponse200) *NullableGetActivityResponse200 {
	return &NullableGetActivityResponse200{value: val, isSet: true}
}

func (v NullableGetActivityResponse200) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetActivityResponse200) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


