/*
Pipedrive API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetRolesResponse200AllOfAdditionalData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRolesResponse200AllOfAdditionalData{}

// GetRolesResponse200AllOfAdditionalData The additional data in the role list
type GetRolesResponse200AllOfAdditionalData struct {
	Pagination *GetRolesResponse200AllOfAdditionalDataPagination `json:"pagination,omitempty"`
}

// NewGetRolesResponse200AllOfAdditionalData instantiates a new GetRolesResponse200AllOfAdditionalData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRolesResponse200AllOfAdditionalData() *GetRolesResponse200AllOfAdditionalData {
	this := GetRolesResponse200AllOfAdditionalData{}
	return &this
}

// NewGetRolesResponse200AllOfAdditionalDataWithDefaults instantiates a new GetRolesResponse200AllOfAdditionalData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRolesResponse200AllOfAdditionalDataWithDefaults() *GetRolesResponse200AllOfAdditionalData {
	this := GetRolesResponse200AllOfAdditionalData{}
	return &this
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *GetRolesResponse200AllOfAdditionalData) GetPagination() GetRolesResponse200AllOfAdditionalDataPagination {
	if o == nil || IsNil(o.Pagination) {
		var ret GetRolesResponse200AllOfAdditionalDataPagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRolesResponse200AllOfAdditionalData) GetPaginationOk() (*GetRolesResponse200AllOfAdditionalDataPagination, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *GetRolesResponse200AllOfAdditionalData) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given GetRolesResponse200AllOfAdditionalDataPagination and assigns it to the Pagination field.
func (o *GetRolesResponse200AllOfAdditionalData) SetPagination(v GetRolesResponse200AllOfAdditionalDataPagination) {
	o.Pagination = &v
}

func (o GetRolesResponse200AllOfAdditionalData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRolesResponse200AllOfAdditionalData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	return toSerialize, nil
}

type NullableGetRolesResponse200AllOfAdditionalData struct {
	value *GetRolesResponse200AllOfAdditionalData
	isSet bool
}

func (v NullableGetRolesResponse200AllOfAdditionalData) Get() *GetRolesResponse200AllOfAdditionalData {
	return v.value
}

func (v *NullableGetRolesResponse200AllOfAdditionalData) Set(val *GetRolesResponse200AllOfAdditionalData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRolesResponse200AllOfAdditionalData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRolesResponse200AllOfAdditionalData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRolesResponse200AllOfAdditionalData(val *GetRolesResponse200AllOfAdditionalData) *NullableGetRolesResponse200AllOfAdditionalData {
	return &NullableGetRolesResponse200AllOfAdditionalData{value: val, isSet: true}
}

func (v NullableGetRolesResponse200AllOfAdditionalData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRolesResponse200AllOfAdditionalData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


