/*
Pipedrive API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddUserProviderLinkRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddUserProviderLinkRequest{}

// AddUserProviderLinkRequest struct for AddUserProviderLinkRequest
type AddUserProviderLinkRequest struct {
	// Unique identifier linking a user to the installed integration. Generated by the integration.
	UserProviderId string `json:"user_provider_id"`
	// Pipedrive user ID
	UserId int32 `json:"user_id"`
	// Pipedrive company ID
	CompanyId int32 `json:"company_id"`
	// Pipedrive Marketplace client ID of the installed integration
	MarketplaceClientId string `json:"marketplace_client_id"`
}

type _AddUserProviderLinkRequest AddUserProviderLinkRequest

// NewAddUserProviderLinkRequest instantiates a new AddUserProviderLinkRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddUserProviderLinkRequest(userProviderId string, userId int32, companyId int32, marketplaceClientId string) *AddUserProviderLinkRequest {
	this := AddUserProviderLinkRequest{}
	this.UserProviderId = userProviderId
	this.UserId = userId
	this.CompanyId = companyId
	this.MarketplaceClientId = marketplaceClientId
	return &this
}

// NewAddUserProviderLinkRequestWithDefaults instantiates a new AddUserProviderLinkRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddUserProviderLinkRequestWithDefaults() *AddUserProviderLinkRequest {
	this := AddUserProviderLinkRequest{}
	return &this
}

// GetUserProviderId returns the UserProviderId field value
func (o *AddUserProviderLinkRequest) GetUserProviderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserProviderId
}

// GetUserProviderIdOk returns a tuple with the UserProviderId field value
// and a boolean to check if the value has been set.
func (o *AddUserProviderLinkRequest) GetUserProviderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserProviderId, true
}

// SetUserProviderId sets field value
func (o *AddUserProviderLinkRequest) SetUserProviderId(v string) {
	o.UserProviderId = v
}

// GetUserId returns the UserId field value
func (o *AddUserProviderLinkRequest) GetUserId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *AddUserProviderLinkRequest) GetUserIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *AddUserProviderLinkRequest) SetUserId(v int32) {
	o.UserId = v
}

// GetCompanyId returns the CompanyId field value
func (o *AddUserProviderLinkRequest) GetCompanyId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CompanyId
}

// GetCompanyIdOk returns a tuple with the CompanyId field value
// and a boolean to check if the value has been set.
func (o *AddUserProviderLinkRequest) GetCompanyIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CompanyId, true
}

// SetCompanyId sets field value
func (o *AddUserProviderLinkRequest) SetCompanyId(v int32) {
	o.CompanyId = v
}

// GetMarketplaceClientId returns the MarketplaceClientId field value
func (o *AddUserProviderLinkRequest) GetMarketplaceClientId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MarketplaceClientId
}

// GetMarketplaceClientIdOk returns a tuple with the MarketplaceClientId field value
// and a boolean to check if the value has been set.
func (o *AddUserProviderLinkRequest) GetMarketplaceClientIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MarketplaceClientId, true
}

// SetMarketplaceClientId sets field value
func (o *AddUserProviderLinkRequest) SetMarketplaceClientId(v string) {
	o.MarketplaceClientId = v
}

func (o AddUserProviderLinkRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddUserProviderLinkRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user_provider_id"] = o.UserProviderId
	toSerialize["user_id"] = o.UserId
	toSerialize["company_id"] = o.CompanyId
	toSerialize["marketplace_client_id"] = o.MarketplaceClientId
	return toSerialize, nil
}

func (o *AddUserProviderLinkRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user_provider_id",
		"user_id",
		"company_id",
		"marketplace_client_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddUserProviderLinkRequest := _AddUserProviderLinkRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddUserProviderLinkRequest)

	if err != nil {
		return err
	}

	*o = AddUserProviderLinkRequest(varAddUserProviderLinkRequest)

	return err
}

type NullableAddUserProviderLinkRequest struct {
	value *AddUserProviderLinkRequest
	isSet bool
}

func (v NullableAddUserProviderLinkRequest) Get() *AddUserProviderLinkRequest {
	return v.value
}

func (v *NullableAddUserProviderLinkRequest) Set(val *AddUserProviderLinkRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddUserProviderLinkRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddUserProviderLinkRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddUserProviderLinkRequest(val *AddUserProviderLinkRequest) *NullableAddUserProviderLinkRequest {
	return &NullableAddUserProviderLinkRequest{value: val, isSet: true}
}

func (v NullableAddUserProviderLinkRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddUserProviderLinkRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


