/*
Pipedrive API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AddPersonFollowerRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddPersonFollowerRequest{}

// AddPersonFollowerRequest struct for AddPersonFollowerRequest
type AddPersonFollowerRequest struct {
	// The ID of the user
	UserId int32 `json:"user_id"`
}

// NewAddPersonFollowerRequest instantiates a new AddPersonFollowerRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddPersonFollowerRequest(userId int32) *AddPersonFollowerRequest {
	this := AddPersonFollowerRequest{}
	this.UserId = userId
	return &this
}

// NewAddPersonFollowerRequestWithDefaults instantiates a new AddPersonFollowerRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddPersonFollowerRequestWithDefaults() *AddPersonFollowerRequest {
	this := AddPersonFollowerRequest{}
	return &this
}

// GetUserId returns the UserId field value
func (o *AddPersonFollowerRequest) GetUserId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *AddPersonFollowerRequest) GetUserIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *AddPersonFollowerRequest) SetUserId(v int32) {
	o.UserId = v
}

func (o AddPersonFollowerRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddPersonFollowerRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user_id"] = o.UserId
	return toSerialize, nil
}

type NullableAddPersonFollowerRequest struct {
	value *AddPersonFollowerRequest
	isSet bool
}

func (v NullableAddPersonFollowerRequest) Get() *AddPersonFollowerRequest {
	return v.value
}

func (v *NullableAddPersonFollowerRequest) Set(val *AddPersonFollowerRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddPersonFollowerRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddPersonFollowerRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddPersonFollowerRequest(val *AddPersonFollowerRequest) *NullableAddPersonFollowerRequest {
	return &NullableAddPersonFollowerRequest{value: val, isSet: true}
}

func (v NullableAddPersonFollowerRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddPersonFollowerRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


