/*
Pipedrive API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetProjectPhasesResponse200 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetProjectPhasesResponse200{}

// GetProjectPhasesResponse200 struct for GetProjectPhasesResponse200
type GetProjectPhasesResponse200 struct {
	Success *bool `json:"success,omitempty"`
	Data []GetProjectPhasesResponse200DataInner `json:"data,omitempty"`
	AdditionalData map[string]interface{} `json:"additional_data,omitempty"`
}

// NewGetProjectPhasesResponse200 instantiates a new GetProjectPhasesResponse200 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetProjectPhasesResponse200() *GetProjectPhasesResponse200 {
	this := GetProjectPhasesResponse200{}
	return &this
}

// NewGetProjectPhasesResponse200WithDefaults instantiates a new GetProjectPhasesResponse200 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetProjectPhasesResponse200WithDefaults() *GetProjectPhasesResponse200 {
	this := GetProjectPhasesResponse200{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetProjectPhasesResponse200) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectPhasesResponse200) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetProjectPhasesResponse200) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GetProjectPhasesResponse200) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetProjectPhasesResponse200) GetData() []GetProjectPhasesResponse200DataInner {
	if o == nil || IsNil(o.Data) {
		var ret []GetProjectPhasesResponse200DataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectPhasesResponse200) GetDataOk() ([]GetProjectPhasesResponse200DataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetProjectPhasesResponse200) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []GetProjectPhasesResponse200DataInner and assigns it to the Data field.
func (o *GetProjectPhasesResponse200) SetData(v []GetProjectPhasesResponse200DataInner) {
	o.Data = v
}

// GetAdditionalData returns the AdditionalData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetProjectPhasesResponse200) GetAdditionalData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.AdditionalData
}

// GetAdditionalDataOk returns a tuple with the AdditionalData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetProjectPhasesResponse200) GetAdditionalDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.AdditionalData) {
		return map[string]interface{}{}, false
	}
	return o.AdditionalData, true
}

// HasAdditionalData returns a boolean if a field has been set.
func (o *GetProjectPhasesResponse200) HasAdditionalData() bool {
	if o != nil && !IsNil(o.AdditionalData) {
		return true
	}

	return false
}

// SetAdditionalData gets a reference to the given map[string]interface{} and assigns it to the AdditionalData field.
func (o *GetProjectPhasesResponse200) SetAdditionalData(v map[string]interface{}) {
	o.AdditionalData = v
}

func (o GetProjectPhasesResponse200) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetProjectPhasesResponse200) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if o.AdditionalData != nil {
		toSerialize["additional_data"] = o.AdditionalData
	}
	return toSerialize, nil
}

type NullableGetProjectPhasesResponse200 struct {
	value *GetProjectPhasesResponse200
	isSet bool
}

func (v NullableGetProjectPhasesResponse200) Get() *GetProjectPhasesResponse200 {
	return v.value
}

func (v *NullableGetProjectPhasesResponse200) Set(val *GetProjectPhasesResponse200) {
	v.value = val
	v.isSet = true
}

func (v NullableGetProjectPhasesResponse200) IsSet() bool {
	return v.isSet
}

func (v *NullableGetProjectPhasesResponse200) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetProjectPhasesResponse200(val *GetProjectPhasesResponse200) *NullableGetProjectPhasesResponse200 {
	return &NullableGetProjectPhasesResponse200{value: val, isSet: true}
}

func (v NullableGetProjectPhasesResponse200) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetProjectPhasesResponse200) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


