/*
Pipedrive API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PipelineDetailsAllOfDealsSummaryPerStages type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PipelineDetailsAllOfDealsSummaryPerStages{}

// PipelineDetailsAllOfDealsSummaryPerStages The stage objects containing deals currency information
type PipelineDetailsAllOfDealsSummaryPerStages struct {
	STAGE_ID *PipelineDetailsAllOfDealsSummaryPerStagesSTAGEID `json:"STAGE_ID,omitempty"`
}

// NewPipelineDetailsAllOfDealsSummaryPerStages instantiates a new PipelineDetailsAllOfDealsSummaryPerStages object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPipelineDetailsAllOfDealsSummaryPerStages() *PipelineDetailsAllOfDealsSummaryPerStages {
	this := PipelineDetailsAllOfDealsSummaryPerStages{}
	return &this
}

// NewPipelineDetailsAllOfDealsSummaryPerStagesWithDefaults instantiates a new PipelineDetailsAllOfDealsSummaryPerStages object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPipelineDetailsAllOfDealsSummaryPerStagesWithDefaults() *PipelineDetailsAllOfDealsSummaryPerStages {
	this := PipelineDetailsAllOfDealsSummaryPerStages{}
	return &this
}

// GetSTAGE_ID returns the STAGE_ID field value if set, zero value otherwise.
func (o *PipelineDetailsAllOfDealsSummaryPerStages) GetSTAGE_ID() PipelineDetailsAllOfDealsSummaryPerStagesSTAGEID {
	if o == nil || IsNil(o.STAGE_ID) {
		var ret PipelineDetailsAllOfDealsSummaryPerStagesSTAGEID
		return ret
	}
	return *o.STAGE_ID
}

// GetSTAGE_IDOk returns a tuple with the STAGE_ID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineDetailsAllOfDealsSummaryPerStages) GetSTAGE_IDOk() (*PipelineDetailsAllOfDealsSummaryPerStagesSTAGEID, bool) {
	if o == nil || IsNil(o.STAGE_ID) {
		return nil, false
	}
	return o.STAGE_ID, true
}

// HasSTAGE_ID returns a boolean if a field has been set.
func (o *PipelineDetailsAllOfDealsSummaryPerStages) HasSTAGE_ID() bool {
	if o != nil && !IsNil(o.STAGE_ID) {
		return true
	}

	return false
}

// SetSTAGE_ID gets a reference to the given PipelineDetailsAllOfDealsSummaryPerStagesSTAGEID and assigns it to the STAGE_ID field.
func (o *PipelineDetailsAllOfDealsSummaryPerStages) SetSTAGE_ID(v PipelineDetailsAllOfDealsSummaryPerStagesSTAGEID) {
	o.STAGE_ID = &v
}

func (o PipelineDetailsAllOfDealsSummaryPerStages) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PipelineDetailsAllOfDealsSummaryPerStages) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.STAGE_ID) {
		toSerialize["STAGE_ID"] = o.STAGE_ID
	}
	return toSerialize, nil
}

type NullablePipelineDetailsAllOfDealsSummaryPerStages struct {
	value *PipelineDetailsAllOfDealsSummaryPerStages
	isSet bool
}

func (v NullablePipelineDetailsAllOfDealsSummaryPerStages) Get() *PipelineDetailsAllOfDealsSummaryPerStages {
	return v.value
}

func (v *NullablePipelineDetailsAllOfDealsSummaryPerStages) Set(val *PipelineDetailsAllOfDealsSummaryPerStages) {
	v.value = val
	v.isSet = true
}

func (v NullablePipelineDetailsAllOfDealsSummaryPerStages) IsSet() bool {
	return v.isSet
}

func (v *NullablePipelineDetailsAllOfDealsSummaryPerStages) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePipelineDetailsAllOfDealsSummaryPerStages(val *PipelineDetailsAllOfDealsSummaryPerStages) *NullablePipelineDetailsAllOfDealsSummaryPerStages {
	return &NullablePipelineDetailsAllOfDealsSummaryPerStages{value: val, isSet: true}
}

func (v NullablePipelineDetailsAllOfDealsSummaryPerStages) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePipelineDetailsAllOfDealsSummaryPerStages) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


