/*
Pipedrive API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AddTaskResponse201 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddTaskResponse201{}

// AddTaskResponse201 struct for AddTaskResponse201
type AddTaskResponse201 struct {
	Success *bool `json:"success,omitempty"`
	Data *TaskResponseObject `json:"data,omitempty"`
	AdditionalData map[string]interface{} `json:"additional_data,omitempty"`
}

// NewAddTaskResponse201 instantiates a new AddTaskResponse201 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddTaskResponse201() *AddTaskResponse201 {
	this := AddTaskResponse201{}
	return &this
}

// NewAddTaskResponse201WithDefaults instantiates a new AddTaskResponse201 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddTaskResponse201WithDefaults() *AddTaskResponse201 {
	this := AddTaskResponse201{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *AddTaskResponse201) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddTaskResponse201) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *AddTaskResponse201) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *AddTaskResponse201) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AddTaskResponse201) GetData() TaskResponseObject {
	if o == nil || IsNil(o.Data) {
		var ret TaskResponseObject
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddTaskResponse201) GetDataOk() (*TaskResponseObject, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AddTaskResponse201) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given TaskResponseObject and assigns it to the Data field.
func (o *AddTaskResponse201) SetData(v TaskResponseObject) {
	o.Data = &v
}

// GetAdditionalData returns the AdditionalData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddTaskResponse201) GetAdditionalData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.AdditionalData
}

// GetAdditionalDataOk returns a tuple with the AdditionalData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddTaskResponse201) GetAdditionalDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.AdditionalData) {
		return map[string]interface{}{}, false
	}
	return o.AdditionalData, true
}

// HasAdditionalData returns a boolean if a field has been set.
func (o *AddTaskResponse201) HasAdditionalData() bool {
	if o != nil && !IsNil(o.AdditionalData) {
		return true
	}

	return false
}

// SetAdditionalData gets a reference to the given map[string]interface{} and assigns it to the AdditionalData field.
func (o *AddTaskResponse201) SetAdditionalData(v map[string]interface{}) {
	o.AdditionalData = v
}

func (o AddTaskResponse201) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddTaskResponse201) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if o.AdditionalData != nil {
		toSerialize["additional_data"] = o.AdditionalData
	}
	return toSerialize, nil
}

type NullableAddTaskResponse201 struct {
	value *AddTaskResponse201
	isSet bool
}

func (v NullableAddTaskResponse201) Get() *AddTaskResponse201 {
	return v.value
}

func (v *NullableAddTaskResponse201) Set(val *AddTaskResponse201) {
	v.value = val
	v.isSet = true
}

func (v NullableAddTaskResponse201) IsSet() bool {
	return v.isSet
}

func (v *NullableAddTaskResponse201) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddTaskResponse201(val *AddTaskResponse201) *NullableAddTaskResponse201 {
	return &NullableAddTaskResponse201{value: val, isSet: true}
}

func (v NullableAddTaskResponse201) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddTaskResponse201) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


