/*
Pipedrive API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the BaseResponse200 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BaseResponse200{}

// BaseResponse200 struct for BaseResponse200
type BaseResponse200 struct {
	// If the response is successful or not
	Success *bool `json:"success,omitempty"`
	// The status of the response
	Status *string `json:"status,omitempty"`
}

// NewBaseResponse200 instantiates a new BaseResponse200 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBaseResponse200() *BaseResponse200 {
	this := BaseResponse200{}
	return &this
}

// NewBaseResponse200WithDefaults instantiates a new BaseResponse200 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBaseResponse200WithDefaults() *BaseResponse200 {
	this := BaseResponse200{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *BaseResponse200) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseResponse200) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *BaseResponse200) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *BaseResponse200) SetSuccess(v bool) {
	o.Success = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *BaseResponse200) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BaseResponse200) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *BaseResponse200) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *BaseResponse200) SetStatus(v string) {
	o.Status = &v
}

func (o BaseResponse200) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BaseResponse200) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableBaseResponse200 struct {
	value *BaseResponse200
	isSet bool
}

func (v NullableBaseResponse200) Get() *BaseResponse200 {
	return v.value
}

func (v *NullableBaseResponse200) Set(val *BaseResponse200) {
	v.value = val
	v.isSet = true
}

func (v NullableBaseResponse200) IsSet() bool {
	return v.isSet
}

func (v *NullableBaseResponse200) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBaseResponse200(val *BaseResponse200) *NullableBaseResponse200 {
	return &NullableBaseResponse200{value: val, isSet: true}
}

func (v NullableBaseResponse200) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBaseResponse200) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


