/*
Pipedrive API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetDealActivitiesResponse200 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDealActivitiesResponse200{}

// GetDealActivitiesResponse200 struct for GetDealActivitiesResponse200
type GetDealActivitiesResponse200 struct {
	// If the response is successful or not
	Success *bool `json:"success,omitempty"`
	// The array of activities
	Data []ActivityResponseObject `json:"data,omitempty"`
	AdditionalData *ActivityDistributionDataWithAdditionalData `json:"additional_data,omitempty"`
	RelatedObjects *GetDealActivitiesResponse200AllOfRelatedObjects `json:"related_objects,omitempty"`
}

// NewGetDealActivitiesResponse200 instantiates a new GetDealActivitiesResponse200 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDealActivitiesResponse200() *GetDealActivitiesResponse200 {
	this := GetDealActivitiesResponse200{}
	return &this
}

// NewGetDealActivitiesResponse200WithDefaults instantiates a new GetDealActivitiesResponse200 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDealActivitiesResponse200WithDefaults() *GetDealActivitiesResponse200 {
	this := GetDealActivitiesResponse200{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetDealActivitiesResponse200) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDealActivitiesResponse200) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetDealActivitiesResponse200) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GetDealActivitiesResponse200) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetDealActivitiesResponse200) GetData() []ActivityResponseObject {
	if o == nil || IsNil(o.Data) {
		var ret []ActivityResponseObject
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDealActivitiesResponse200) GetDataOk() ([]ActivityResponseObject, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetDealActivitiesResponse200) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []ActivityResponseObject and assigns it to the Data field.
func (o *GetDealActivitiesResponse200) SetData(v []ActivityResponseObject) {
	o.Data = v
}

// GetAdditionalData returns the AdditionalData field value if set, zero value otherwise.
func (o *GetDealActivitiesResponse200) GetAdditionalData() ActivityDistributionDataWithAdditionalData {
	if o == nil || IsNil(o.AdditionalData) {
		var ret ActivityDistributionDataWithAdditionalData
		return ret
	}
	return *o.AdditionalData
}

// GetAdditionalDataOk returns a tuple with the AdditionalData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDealActivitiesResponse200) GetAdditionalDataOk() (*ActivityDistributionDataWithAdditionalData, bool) {
	if o == nil || IsNil(o.AdditionalData) {
		return nil, false
	}
	return o.AdditionalData, true
}

// HasAdditionalData returns a boolean if a field has been set.
func (o *GetDealActivitiesResponse200) HasAdditionalData() bool {
	if o != nil && !IsNil(o.AdditionalData) {
		return true
	}

	return false
}

// SetAdditionalData gets a reference to the given ActivityDistributionDataWithAdditionalData and assigns it to the AdditionalData field.
func (o *GetDealActivitiesResponse200) SetAdditionalData(v ActivityDistributionDataWithAdditionalData) {
	o.AdditionalData = &v
}

// GetRelatedObjects returns the RelatedObjects field value if set, zero value otherwise.
func (o *GetDealActivitiesResponse200) GetRelatedObjects() GetDealActivitiesResponse200AllOfRelatedObjects {
	if o == nil || IsNil(o.RelatedObjects) {
		var ret GetDealActivitiesResponse200AllOfRelatedObjects
		return ret
	}
	return *o.RelatedObjects
}

// GetRelatedObjectsOk returns a tuple with the RelatedObjects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDealActivitiesResponse200) GetRelatedObjectsOk() (*GetDealActivitiesResponse200AllOfRelatedObjects, bool) {
	if o == nil || IsNil(o.RelatedObjects) {
		return nil, false
	}
	return o.RelatedObjects, true
}

// HasRelatedObjects returns a boolean if a field has been set.
func (o *GetDealActivitiesResponse200) HasRelatedObjects() bool {
	if o != nil && !IsNil(o.RelatedObjects) {
		return true
	}

	return false
}

// SetRelatedObjects gets a reference to the given GetDealActivitiesResponse200AllOfRelatedObjects and assigns it to the RelatedObjects field.
func (o *GetDealActivitiesResponse200) SetRelatedObjects(v GetDealActivitiesResponse200AllOfRelatedObjects) {
	o.RelatedObjects = &v
}

func (o GetDealActivitiesResponse200) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDealActivitiesResponse200) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.AdditionalData) {
		toSerialize["additional_data"] = o.AdditionalData
	}
	if !IsNil(o.RelatedObjects) {
		toSerialize["related_objects"] = o.RelatedObjects
	}
	return toSerialize, nil
}

type NullableGetDealActivitiesResponse200 struct {
	value *GetDealActivitiesResponse200
	isSet bool
}

func (v NullableGetDealActivitiesResponse200) Get() *GetDealActivitiesResponse200 {
	return v.value
}

func (v *NullableGetDealActivitiesResponse200) Set(val *GetDealActivitiesResponse200) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDealActivitiesResponse200) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDealActivitiesResponse200) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDealActivitiesResponse200(val *GetDealActivitiesResponse200) *NullableGetDealActivitiesResponse200 {
	return &NullableGetDealActivitiesResponse200{value: val, isSet: true}
}

func (v NullableGetDealActivitiesResponse200) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDealActivitiesResponse200) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


