/*
Pipedrive API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DeleteDealProductResponse200Data type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteDealProductResponse200Data{}

// DeleteDealProductResponse200Data struct for DeleteDealProductResponse200Data
type DeleteDealProductResponse200Data struct {
	// The ID of an attached product that was deleted from the deal
	Id *int32 `json:"id,omitempty"`
}

// NewDeleteDealProductResponse200Data instantiates a new DeleteDealProductResponse200Data object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteDealProductResponse200Data() *DeleteDealProductResponse200Data {
	this := DeleteDealProductResponse200Data{}
	return &this
}

// NewDeleteDealProductResponse200DataWithDefaults instantiates a new DeleteDealProductResponse200Data object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteDealProductResponse200DataWithDefaults() *DeleteDealProductResponse200Data {
	this := DeleteDealProductResponse200Data{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DeleteDealProductResponse200Data) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteDealProductResponse200Data) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DeleteDealProductResponse200Data) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *DeleteDealProductResponse200Data) SetId(v int32) {
	o.Id = &v
}

func (o DeleteDealProductResponse200Data) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteDealProductResponse200Data) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableDeleteDealProductResponse200Data struct {
	value *DeleteDealProductResponse200Data
	isSet bool
}

func (v NullableDeleteDealProductResponse200Data) Get() *DeleteDealProductResponse200Data {
	return v.value
}

func (v *NullableDeleteDealProductResponse200Data) Set(val *DeleteDealProductResponse200Data) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteDealProductResponse200Data) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteDealProductResponse200Data) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteDealProductResponse200Data(val *DeleteDealProductResponse200Data) *NullableDeleteDealProductResponse200Data {
	return &NullableDeleteDealProductResponse200Data{value: val, isSet: true}
}

func (v NullableDeleteDealProductResponse200Data) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteDealProductResponse200Data) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


