/*
Pipedrive API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetPersonResponse200 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPersonResponse200{}

// GetPersonResponse200 struct for GetPersonResponse200
type GetPersonResponse200 struct {
	// If the response is successful or not
	Success *bool `json:"success,omitempty"`
	Data *PersonItem `json:"data,omitempty"`
	AdditionalData *GetPersonResponse200AllOfAdditionalData `json:"additional_data,omitempty"`
	RelatedObjects *GetOrganizationsResponse200AllOfRelatedObjects `json:"related_objects,omitempty"`
}

// NewGetPersonResponse200 instantiates a new GetPersonResponse200 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPersonResponse200() *GetPersonResponse200 {
	this := GetPersonResponse200{}
	return &this
}

// NewGetPersonResponse200WithDefaults instantiates a new GetPersonResponse200 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPersonResponse200WithDefaults() *GetPersonResponse200 {
	this := GetPersonResponse200{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetPersonResponse200) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPersonResponse200) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetPersonResponse200) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GetPersonResponse200) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetPersonResponse200) GetData() PersonItem {
	if o == nil || IsNil(o.Data) {
		var ret PersonItem
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPersonResponse200) GetDataOk() (*PersonItem, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetPersonResponse200) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given PersonItem and assigns it to the Data field.
func (o *GetPersonResponse200) SetData(v PersonItem) {
	o.Data = &v
}

// GetAdditionalData returns the AdditionalData field value if set, zero value otherwise.
func (o *GetPersonResponse200) GetAdditionalData() GetPersonResponse200AllOfAdditionalData {
	if o == nil || IsNil(o.AdditionalData) {
		var ret GetPersonResponse200AllOfAdditionalData
		return ret
	}
	return *o.AdditionalData
}

// GetAdditionalDataOk returns a tuple with the AdditionalData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPersonResponse200) GetAdditionalDataOk() (*GetPersonResponse200AllOfAdditionalData, bool) {
	if o == nil || IsNil(o.AdditionalData) {
		return nil, false
	}
	return o.AdditionalData, true
}

// HasAdditionalData returns a boolean if a field has been set.
func (o *GetPersonResponse200) HasAdditionalData() bool {
	if o != nil && !IsNil(o.AdditionalData) {
		return true
	}

	return false
}

// SetAdditionalData gets a reference to the given GetPersonResponse200AllOfAdditionalData and assigns it to the AdditionalData field.
func (o *GetPersonResponse200) SetAdditionalData(v GetPersonResponse200AllOfAdditionalData) {
	o.AdditionalData = &v
}

// GetRelatedObjects returns the RelatedObjects field value if set, zero value otherwise.
func (o *GetPersonResponse200) GetRelatedObjects() GetOrganizationsResponse200AllOfRelatedObjects {
	if o == nil || IsNil(o.RelatedObjects) {
		var ret GetOrganizationsResponse200AllOfRelatedObjects
		return ret
	}
	return *o.RelatedObjects
}

// GetRelatedObjectsOk returns a tuple with the RelatedObjects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPersonResponse200) GetRelatedObjectsOk() (*GetOrganizationsResponse200AllOfRelatedObjects, bool) {
	if o == nil || IsNil(o.RelatedObjects) {
		return nil, false
	}
	return o.RelatedObjects, true
}

// HasRelatedObjects returns a boolean if a field has been set.
func (o *GetPersonResponse200) HasRelatedObjects() bool {
	if o != nil && !IsNil(o.RelatedObjects) {
		return true
	}

	return false
}

// SetRelatedObjects gets a reference to the given GetOrganizationsResponse200AllOfRelatedObjects and assigns it to the RelatedObjects field.
func (o *GetPersonResponse200) SetRelatedObjects(v GetOrganizationsResponse200AllOfRelatedObjects) {
	o.RelatedObjects = &v
}

func (o GetPersonResponse200) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPersonResponse200) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.AdditionalData) {
		toSerialize["additional_data"] = o.AdditionalData
	}
	if !IsNil(o.RelatedObjects) {
		toSerialize["related_objects"] = o.RelatedObjects
	}
	return toSerialize, nil
}

type NullableGetPersonResponse200 struct {
	value *GetPersonResponse200
	isSet bool
}

func (v NullableGetPersonResponse200) Get() *GetPersonResponse200 {
	return v.value
}

func (v *NullableGetPersonResponse200) Set(val *GetPersonResponse200) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPersonResponse200) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPersonResponse200) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPersonResponse200(val *GetPersonResponse200) *NullableGetPersonResponse200 {
	return &NullableGetPersonResponse200{value: val, isSet: true}
}

func (v NullableGetPersonResponse200) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPersonResponse200) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


