/*
Pipedrive API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DealUserDataWithId type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DealUserDataWithId{}

// DealUserDataWithId struct for DealUserDataWithId
type DealUserDataWithId struct {
	// The ID of the user
	Id *int32 `json:"id,omitempty"`
	// The name of the user
	Name *string `json:"name,omitempty"`
	// The email of the user
	Email *string `json:"email,omitempty"`
	// If the user has a picture or not
	HasPic *int32 `json:"has_pic,omitempty"`
	// The user picture hash
	PicHash NullableString `json:"pic_hash,omitempty"`
	// Whether the user is active or not
	ActiveFlag *bool `json:"active_flag,omitempty"`
	// The ID of the user
	Value *int32 `json:"value,omitempty"`
}

// NewDealUserDataWithId instantiates a new DealUserDataWithId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDealUserDataWithId() *DealUserDataWithId {
	this := DealUserDataWithId{}
	return &this
}

// NewDealUserDataWithIdWithDefaults instantiates a new DealUserDataWithId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDealUserDataWithIdWithDefaults() *DealUserDataWithId {
	this := DealUserDataWithId{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DealUserDataWithId) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DealUserDataWithId) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DealUserDataWithId) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *DealUserDataWithId) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DealUserDataWithId) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DealUserDataWithId) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DealUserDataWithId) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DealUserDataWithId) SetName(v string) {
	o.Name = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *DealUserDataWithId) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DealUserDataWithId) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *DealUserDataWithId) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *DealUserDataWithId) SetEmail(v string) {
	o.Email = &v
}

// GetHasPic returns the HasPic field value if set, zero value otherwise.
func (o *DealUserDataWithId) GetHasPic() int32 {
	if o == nil || IsNil(o.HasPic) {
		var ret int32
		return ret
	}
	return *o.HasPic
}

// GetHasPicOk returns a tuple with the HasPic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DealUserDataWithId) GetHasPicOk() (*int32, bool) {
	if o == nil || IsNil(o.HasPic) {
		return nil, false
	}
	return o.HasPic, true
}

// HasHasPic returns a boolean if a field has been set.
func (o *DealUserDataWithId) HasHasPic() bool {
	if o != nil && !IsNil(o.HasPic) {
		return true
	}

	return false
}

// SetHasPic gets a reference to the given bool and assigns it to the HasPic field.
func (o *DealUserDataWithId) SetHasPic(v int32) {
	o.HasPic = &v
}

// GetPicHash returns the PicHash field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DealUserDataWithId) GetPicHash() string {
	if o == nil || IsNil(o.PicHash.Get()) {
		var ret string
		return ret
	}
	return *o.PicHash.Get()
}

// GetPicHashOk returns a tuple with the PicHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DealUserDataWithId) GetPicHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PicHash.Get(), o.PicHash.IsSet()
}

// HasPicHash returns a boolean if a field has been set.
func (o *DealUserDataWithId) HasPicHash() bool {
	if o != nil && o.PicHash.IsSet() {
		return true
	}

	return false
}

// SetPicHash gets a reference to the given NullableString and assigns it to the PicHash field.
func (o *DealUserDataWithId) SetPicHash(v string) {
	o.PicHash.Set(&v)
}
// SetPicHashNil sets the value for PicHash to be an explicit nil
func (o *DealUserDataWithId) SetPicHashNil() {
	o.PicHash.Set(nil)
}

// UnsetPicHash ensures that no value is present for PicHash, not even an explicit nil
func (o *DealUserDataWithId) UnsetPicHash() {
	o.PicHash.Unset()
}

// GetActiveFlag returns the ActiveFlag field value if set, zero value otherwise.
func (o *DealUserDataWithId) GetActiveFlag() bool {
	if o == nil || IsNil(o.ActiveFlag) {
		var ret bool
		return ret
	}
	return *o.ActiveFlag
}

// GetActiveFlagOk returns a tuple with the ActiveFlag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DealUserDataWithId) GetActiveFlagOk() (*bool, bool) {
	if o == nil || IsNil(o.ActiveFlag) {
		return nil, false
	}
	return o.ActiveFlag, true
}

// HasActiveFlag returns a boolean if a field has been set.
func (o *DealUserDataWithId) HasActiveFlag() bool {
	if o != nil && !IsNil(o.ActiveFlag) {
		return true
	}

	return false
}

// SetActiveFlag gets a reference to the given bool and assigns it to the ActiveFlag field.
func (o *DealUserDataWithId) SetActiveFlag(v bool) {
	o.ActiveFlag = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *DealUserDataWithId) GetValue() int32 {
	if o == nil || IsNil(o.Value) {
		var ret int32
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DealUserDataWithId) GetValueOk() (*int32, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *DealUserDataWithId) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given int32 and assigns it to the Value field.
func (o *DealUserDataWithId) SetValue(v int32) {
	o.Value = &v
}

func (o DealUserDataWithId) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DealUserDataWithId) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.HasPic) {
		toSerialize["has_pic"] = o.HasPic
	}
	if o.PicHash.IsSet() {
		toSerialize["pic_hash"] = o.PicHash.Get()
	}
	if !IsNil(o.ActiveFlag) {
		toSerialize["active_flag"] = o.ActiveFlag
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableDealUserDataWithId struct {
	value *DealUserDataWithId
	isSet bool
}

func (v NullableDealUserDataWithId) Get() *DealUserDataWithId {
	return v.value
}

func (v *NullableDealUserDataWithId) Set(val *DealUserDataWithId) {
	v.value = val
	v.isSet = true
}

func (v NullableDealUserDataWithId) IsSet() bool {
	return v.isSet
}

func (v *NullableDealUserDataWithId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDealUserDataWithId(val *DealUserDataWithId) *NullableDealUserDataWithId {
	return &NullableDealUserDataWithId{value: val, isSet: true}
}

func (v NullableDealUserDataWithId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDealUserDataWithId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


