/*
Pipedrive API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetCurrentUserResponse200AllOfData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCurrentUserResponse200AllOfData{}

// GetCurrentUserResponse200AllOfData struct for GetCurrentUserResponse200AllOfData
type GetCurrentUserResponse200AllOfData struct {
	// The user ID
	Id *int32 `json:"id,omitempty"`
	// The user name
	Name *string `json:"name,omitempty"`
	// The user default currency
	DefaultCurrency *string `json:"default_currency,omitempty"`
	// The user locale
	Locale *string `json:"locale,omitempty"`
	// The user language ID
	Lang *int32 `json:"lang,omitempty"`
	// The user email
	Email *string `json:"email,omitempty"`
	// The user phone
	Phone NullableString `json:"phone,omitempty"`
	// Boolean that indicates whether the user is activated
	Activated *bool `json:"activated,omitempty"`
	// The last login date and time of the user. Format: YYYY-MM-DD HH:MM:SS
	LastLogin *string `json:"last_login,omitempty"`
	// The creation date and time of the user. Format: YYYY-MM-DD HH:MM:SS
	Created *string `json:"created,omitempty"`
	// The last modification date and time of the user. Format: YYYY-MM-DD HH:MM:SS
	Modified NullableString `json:"modified,omitempty"`
	// Boolean that indicates whether the user has created a company
	HasCreatedCompany *bool `json:"has_created_company,omitempty"`
	Access []GetRecentsResponse200DataInnerAnyOf11DataAccessInner `json:"access,omitempty"`
	// Boolean that indicates whether the user is activated
	ActiveFlag *bool `json:"active_flag,omitempty"`
	// The user timezone name
	TimezoneName *string `json:"timezone_name,omitempty"`
	// The user timezone offset
	TimezoneOffset *string `json:"timezone_offset,omitempty"`
	// The ID of the user role
	RoleId *int32 `json:"role_id,omitempty"`
	// The user icon URL
	IconUrl NullableString `json:"icon_url,omitempty"`
	// Boolean that indicates if the requested user is the same which is logged in (in this case, always true)
	IsYou *bool `json:"is_you,omitempty"`
	// Boolean that indicates whether the user is deleted from the company
	IsDeleted *bool `json:"is_deleted,omitempty"`
	// The user company ID
	CompanyId *int32 `json:"company_id,omitempty"`
	// The user company name
	CompanyName *string `json:"company_name,omitempty"`
	// The user company domain
	CompanyDomain *string `json:"company_domain,omitempty"`
	// The user company country
	CompanyCountry *string `json:"company_country,omitempty"`
	// The user company industry
	CompanyIndustry *string `json:"company_industry,omitempty"`
	Language *GetCurrentUserResponse200AllOfDataAllOfLanguage `json:"language,omitempty"`
}

// NewGetCurrentUserResponse200AllOfData instantiates a new GetCurrentUserResponse200AllOfData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCurrentUserResponse200AllOfData() *GetCurrentUserResponse200AllOfData {
	this := GetCurrentUserResponse200AllOfData{}
	return &this
}

// NewGetCurrentUserResponse200AllOfDataWithDefaults instantiates a new GetCurrentUserResponse200AllOfData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCurrentUserResponse200AllOfDataWithDefaults() *GetCurrentUserResponse200AllOfData {
	this := GetCurrentUserResponse200AllOfData{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetCurrentUserResponse200AllOfData) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUserResponse200AllOfData) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetCurrentUserResponse200AllOfData) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GetCurrentUserResponse200AllOfData) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetCurrentUserResponse200AllOfData) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUserResponse200AllOfData) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetCurrentUserResponse200AllOfData) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetCurrentUserResponse200AllOfData) SetName(v string) {
	o.Name = &v
}

// GetDefaultCurrency returns the DefaultCurrency field value if set, zero value otherwise.
func (o *GetCurrentUserResponse200AllOfData) GetDefaultCurrency() string {
	if o == nil || IsNil(o.DefaultCurrency) {
		var ret string
		return ret
	}
	return *o.DefaultCurrency
}

// GetDefaultCurrencyOk returns a tuple with the DefaultCurrency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUserResponse200AllOfData) GetDefaultCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultCurrency) {
		return nil, false
	}
	return o.DefaultCurrency, true
}

// HasDefaultCurrency returns a boolean if a field has been set.
func (o *GetCurrentUserResponse200AllOfData) HasDefaultCurrency() bool {
	if o != nil && !IsNil(o.DefaultCurrency) {
		return true
	}

	return false
}

// SetDefaultCurrency gets a reference to the given string and assigns it to the DefaultCurrency field.
func (o *GetCurrentUserResponse200AllOfData) SetDefaultCurrency(v string) {
	o.DefaultCurrency = &v
}

// GetLocale returns the Locale field value if set, zero value otherwise.
func (o *GetCurrentUserResponse200AllOfData) GetLocale() string {
	if o == nil || IsNil(o.Locale) {
		var ret string
		return ret
	}
	return *o.Locale
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUserResponse200AllOfData) GetLocaleOk() (*string, bool) {
	if o == nil || IsNil(o.Locale) {
		return nil, false
	}
	return o.Locale, true
}

// HasLocale returns a boolean if a field has been set.
func (o *GetCurrentUserResponse200AllOfData) HasLocale() bool {
	if o != nil && !IsNil(o.Locale) {
		return true
	}

	return false
}

// SetLocale gets a reference to the given string and assigns it to the Locale field.
func (o *GetCurrentUserResponse200AllOfData) SetLocale(v string) {
	o.Locale = &v
}

// GetLang returns the Lang field value if set, zero value otherwise.
func (o *GetCurrentUserResponse200AllOfData) GetLang() int32 {
	if o == nil || IsNil(o.Lang) {
		var ret int32
		return ret
	}
	return *o.Lang
}

// GetLangOk returns a tuple with the Lang field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUserResponse200AllOfData) GetLangOk() (*int32, bool) {
	if o == nil || IsNil(o.Lang) {
		return nil, false
	}
	return o.Lang, true
}

// HasLang returns a boolean if a field has been set.
func (o *GetCurrentUserResponse200AllOfData) HasLang() bool {
	if o != nil && !IsNil(o.Lang) {
		return true
	}

	return false
}

// SetLang gets a reference to the given int32 and assigns it to the Lang field.
func (o *GetCurrentUserResponse200AllOfData) SetLang(v int32) {
	o.Lang = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *GetCurrentUserResponse200AllOfData) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUserResponse200AllOfData) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *GetCurrentUserResponse200AllOfData) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *GetCurrentUserResponse200AllOfData) SetEmail(v string) {
	o.Email = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCurrentUserResponse200AllOfData) GetPhone() string {
	if o == nil || IsNil(o.Phone.Get()) {
		var ret string
		return ret
	}
	return *o.Phone.Get()
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCurrentUserResponse200AllOfData) GetPhoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Phone.Get(), o.Phone.IsSet()
}

// HasPhone returns a boolean if a field has been set.
func (o *GetCurrentUserResponse200AllOfData) HasPhone() bool {
	if o != nil && o.Phone.IsSet() {
		return true
	}

	return false
}

// SetPhone gets a reference to the given NullableString and assigns it to the Phone field.
func (o *GetCurrentUserResponse200AllOfData) SetPhone(v string) {
	o.Phone.Set(&v)
}
// SetPhoneNil sets the value for Phone to be an explicit nil
func (o *GetCurrentUserResponse200AllOfData) SetPhoneNil() {
	o.Phone.Set(nil)
}

// UnsetPhone ensures that no value is present for Phone, not even an explicit nil
func (o *GetCurrentUserResponse200AllOfData) UnsetPhone() {
	o.Phone.Unset()
}

// GetActivated returns the Activated field value if set, zero value otherwise.
func (o *GetCurrentUserResponse200AllOfData) GetActivated() bool {
	if o == nil || IsNil(o.Activated) {
		var ret bool
		return ret
	}
	return *o.Activated
}

// GetActivatedOk returns a tuple with the Activated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUserResponse200AllOfData) GetActivatedOk() (*bool, bool) {
	if o == nil || IsNil(o.Activated) {
		return nil, false
	}
	return o.Activated, true
}

// HasActivated returns a boolean if a field has been set.
func (o *GetCurrentUserResponse200AllOfData) HasActivated() bool {
	if o != nil && !IsNil(o.Activated) {
		return true
	}

	return false
}

// SetActivated gets a reference to the given bool and assigns it to the Activated field.
func (o *GetCurrentUserResponse200AllOfData) SetActivated(v bool) {
	o.Activated = &v
}

// GetLastLogin returns the LastLogin field value if set, zero value otherwise.
func (o *GetCurrentUserResponse200AllOfData) GetLastLogin() string {
	if o == nil || IsNil(o.LastLogin) {
		var ret string
		return ret
	}
	return *o.LastLogin
}

// GetLastLoginOk returns a tuple with the LastLogin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUserResponse200AllOfData) GetLastLoginOk() (*string, bool) {
	if o == nil || IsNil(o.LastLogin) {
		return nil, false
	}
	return o.LastLogin, true
}

// HasLastLogin returns a boolean if a field has been set.
func (o *GetCurrentUserResponse200AllOfData) HasLastLogin() bool {
	if o != nil && !IsNil(o.LastLogin) {
		return true
	}

	return false
}

// SetLastLogin gets a reference to the given string and assigns it to the LastLogin field.
func (o *GetCurrentUserResponse200AllOfData) SetLastLogin(v string) {
	o.LastLogin = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *GetCurrentUserResponse200AllOfData) GetCreated() string {
	if o == nil || IsNil(o.Created) {
		var ret string
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUserResponse200AllOfData) GetCreatedOk() (*string, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *GetCurrentUserResponse200AllOfData) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given string and assigns it to the Created field.
func (o *GetCurrentUserResponse200AllOfData) SetCreated(v string) {
	o.Created = &v
}

// GetModified returns the Modified field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCurrentUserResponse200AllOfData) GetModified() string {
	if o == nil || IsNil(o.Modified.Get()) {
		var ret string
		return ret
	}
	return *o.Modified.Get()
}

// GetModifiedOk returns a tuple with the Modified field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCurrentUserResponse200AllOfData) GetModifiedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Modified.Get(), o.Modified.IsSet()
}

// HasModified returns a boolean if a field has been set.
func (o *GetCurrentUserResponse200AllOfData) HasModified() bool {
	if o != nil && o.Modified.IsSet() {
		return true
	}

	return false
}

// SetModified gets a reference to the given NullableString and assigns it to the Modified field.
func (o *GetCurrentUserResponse200AllOfData) SetModified(v string) {
	o.Modified.Set(&v)
}
// SetModifiedNil sets the value for Modified to be an explicit nil
func (o *GetCurrentUserResponse200AllOfData) SetModifiedNil() {
	o.Modified.Set(nil)
}

// UnsetModified ensures that no value is present for Modified, not even an explicit nil
func (o *GetCurrentUserResponse200AllOfData) UnsetModified() {
	o.Modified.Unset()
}

// GetHasCreatedCompany returns the HasCreatedCompany field value if set, zero value otherwise.
func (o *GetCurrentUserResponse200AllOfData) GetHasCreatedCompany() bool {
	if o == nil || IsNil(o.HasCreatedCompany) {
		var ret bool
		return ret
	}
	return *o.HasCreatedCompany
}

// GetHasCreatedCompanyOk returns a tuple with the HasCreatedCompany field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUserResponse200AllOfData) GetHasCreatedCompanyOk() (*bool, bool) {
	if o == nil || IsNil(o.HasCreatedCompany) {
		return nil, false
	}
	return o.HasCreatedCompany, true
}

// HasHasCreatedCompany returns a boolean if a field has been set.
func (o *GetCurrentUserResponse200AllOfData) HasHasCreatedCompany() bool {
	if o != nil && !IsNil(o.HasCreatedCompany) {
		return true
	}

	return false
}

// SetHasCreatedCompany gets a reference to the given bool and assigns it to the HasCreatedCompany field.
func (o *GetCurrentUserResponse200AllOfData) SetHasCreatedCompany(v bool) {
	o.HasCreatedCompany = &v
}

// GetAccess returns the Access field value if set, zero value otherwise.
func (o *GetCurrentUserResponse200AllOfData) GetAccess() []GetRecentsResponse200DataInnerAnyOf11DataAccessInner {
	if o == nil || IsNil(o.Access) {
		var ret []GetRecentsResponse200DataInnerAnyOf11DataAccessInner
		return ret
	}
	return o.Access
}

// GetAccessOk returns a tuple with the Access field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUserResponse200AllOfData) GetAccessOk() ([]GetRecentsResponse200DataInnerAnyOf11DataAccessInner, bool) {
	if o == nil || IsNil(o.Access) {
		return nil, false
	}
	return o.Access, true
}

// HasAccess returns a boolean if a field has been set.
func (o *GetCurrentUserResponse200AllOfData) HasAccess() bool {
	if o != nil && !IsNil(o.Access) {
		return true
	}

	return false
}

// SetAccess gets a reference to the given []GetRecentsResponse200DataInnerAnyOf11DataAccessInner and assigns it to the Access field.
func (o *GetCurrentUserResponse200AllOfData) SetAccess(v []GetRecentsResponse200DataInnerAnyOf11DataAccessInner) {
	o.Access = v
}

// GetActiveFlag returns the ActiveFlag field value if set, zero value otherwise.
func (o *GetCurrentUserResponse200AllOfData) GetActiveFlag() bool {
	if o == nil || IsNil(o.ActiveFlag) {
		var ret bool
		return ret
	}
	return *o.ActiveFlag
}

// GetActiveFlagOk returns a tuple with the ActiveFlag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUserResponse200AllOfData) GetActiveFlagOk() (*bool, bool) {
	if o == nil || IsNil(o.ActiveFlag) {
		return nil, false
	}
	return o.ActiveFlag, true
}

// HasActiveFlag returns a boolean if a field has been set.
func (o *GetCurrentUserResponse200AllOfData) HasActiveFlag() bool {
	if o != nil && !IsNil(o.ActiveFlag) {
		return true
	}

	return false
}

// SetActiveFlag gets a reference to the given bool and assigns it to the ActiveFlag field.
func (o *GetCurrentUserResponse200AllOfData) SetActiveFlag(v bool) {
	o.ActiveFlag = &v
}

// GetTimezoneName returns the TimezoneName field value if set, zero value otherwise.
func (o *GetCurrentUserResponse200AllOfData) GetTimezoneName() string {
	if o == nil || IsNil(o.TimezoneName) {
		var ret string
		return ret
	}
	return *o.TimezoneName
}

// GetTimezoneNameOk returns a tuple with the TimezoneName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUserResponse200AllOfData) GetTimezoneNameOk() (*string, bool) {
	if o == nil || IsNil(o.TimezoneName) {
		return nil, false
	}
	return o.TimezoneName, true
}

// HasTimezoneName returns a boolean if a field has been set.
func (o *GetCurrentUserResponse200AllOfData) HasTimezoneName() bool {
	if o != nil && !IsNil(o.TimezoneName) {
		return true
	}

	return false
}

// SetTimezoneName gets a reference to the given string and assigns it to the TimezoneName field.
func (o *GetCurrentUserResponse200AllOfData) SetTimezoneName(v string) {
	o.TimezoneName = &v
}

// GetTimezoneOffset returns the TimezoneOffset field value if set, zero value otherwise.
func (o *GetCurrentUserResponse200AllOfData) GetTimezoneOffset() string {
	if o == nil || IsNil(o.TimezoneOffset) {
		var ret string
		return ret
	}
	return *o.TimezoneOffset
}

// GetTimezoneOffsetOk returns a tuple with the TimezoneOffset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUserResponse200AllOfData) GetTimezoneOffsetOk() (*string, bool) {
	if o == nil || IsNil(o.TimezoneOffset) {
		return nil, false
	}
	return o.TimezoneOffset, true
}

// HasTimezoneOffset returns a boolean if a field has been set.
func (o *GetCurrentUserResponse200AllOfData) HasTimezoneOffset() bool {
	if o != nil && !IsNil(o.TimezoneOffset) {
		return true
	}

	return false
}

// SetTimezoneOffset gets a reference to the given string and assigns it to the TimezoneOffset field.
func (o *GetCurrentUserResponse200AllOfData) SetTimezoneOffset(v string) {
	o.TimezoneOffset = &v
}

// GetRoleId returns the RoleId field value if set, zero value otherwise.
func (o *GetCurrentUserResponse200AllOfData) GetRoleId() int32 {
	if o == nil || IsNil(o.RoleId) {
		var ret int32
		return ret
	}
	return *o.RoleId
}

// GetRoleIdOk returns a tuple with the RoleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUserResponse200AllOfData) GetRoleIdOk() (*int32, bool) {
	if o == nil || IsNil(o.RoleId) {
		return nil, false
	}
	return o.RoleId, true
}

// HasRoleId returns a boolean if a field has been set.
func (o *GetCurrentUserResponse200AllOfData) HasRoleId() bool {
	if o != nil && !IsNil(o.RoleId) {
		return true
	}

	return false
}

// SetRoleId gets a reference to the given int32 and assigns it to the RoleId field.
func (o *GetCurrentUserResponse200AllOfData) SetRoleId(v int32) {
	o.RoleId = &v
}

// GetIconUrl returns the IconUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetCurrentUserResponse200AllOfData) GetIconUrl() string {
	if o == nil || IsNil(o.IconUrl.Get()) {
		var ret string
		return ret
	}
	return *o.IconUrl.Get()
}

// GetIconUrlOk returns a tuple with the IconUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetCurrentUserResponse200AllOfData) GetIconUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IconUrl.Get(), o.IconUrl.IsSet()
}

// HasIconUrl returns a boolean if a field has been set.
func (o *GetCurrentUserResponse200AllOfData) HasIconUrl() bool {
	if o != nil && o.IconUrl.IsSet() {
		return true
	}

	return false
}

// SetIconUrl gets a reference to the given NullableString and assigns it to the IconUrl field.
func (o *GetCurrentUserResponse200AllOfData) SetIconUrl(v string) {
	o.IconUrl.Set(&v)
}
// SetIconUrlNil sets the value for IconUrl to be an explicit nil
func (o *GetCurrentUserResponse200AllOfData) SetIconUrlNil() {
	o.IconUrl.Set(nil)
}

// UnsetIconUrl ensures that no value is present for IconUrl, not even an explicit nil
func (o *GetCurrentUserResponse200AllOfData) UnsetIconUrl() {
	o.IconUrl.Unset()
}

// GetIsYou returns the IsYou field value if set, zero value otherwise.
func (o *GetCurrentUserResponse200AllOfData) GetIsYou() bool {
	if o == nil || IsNil(o.IsYou) {
		var ret bool
		return ret
	}
	return *o.IsYou
}

// GetIsYouOk returns a tuple with the IsYou field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUserResponse200AllOfData) GetIsYouOk() (*bool, bool) {
	if o == nil || IsNil(o.IsYou) {
		return nil, false
	}
	return o.IsYou, true
}

// HasIsYou returns a boolean if a field has been set.
func (o *GetCurrentUserResponse200AllOfData) HasIsYou() bool {
	if o != nil && !IsNil(o.IsYou) {
		return true
	}

	return false
}

// SetIsYou gets a reference to the given bool and assigns it to the IsYou field.
func (o *GetCurrentUserResponse200AllOfData) SetIsYou(v bool) {
	o.IsYou = &v
}

// GetIsDeleted returns the IsDeleted field value if set, zero value otherwise.
func (o *GetCurrentUserResponse200AllOfData) GetIsDeleted() bool {
	if o == nil || IsNil(o.IsDeleted) {
		var ret bool
		return ret
	}
	return *o.IsDeleted
}

// GetIsDeletedOk returns a tuple with the IsDeleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUserResponse200AllOfData) GetIsDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDeleted) {
		return nil, false
	}
	return o.IsDeleted, true
}

// HasIsDeleted returns a boolean if a field has been set.
func (o *GetCurrentUserResponse200AllOfData) HasIsDeleted() bool {
	if o != nil && !IsNil(o.IsDeleted) {
		return true
	}

	return false
}

// SetIsDeleted gets a reference to the given bool and assigns it to the IsDeleted field.
func (o *GetCurrentUserResponse200AllOfData) SetIsDeleted(v bool) {
	o.IsDeleted = &v
}

// GetCompanyId returns the CompanyId field value if set, zero value otherwise.
func (o *GetCurrentUserResponse200AllOfData) GetCompanyId() int32 {
	if o == nil || IsNil(o.CompanyId) {
		var ret int32
		return ret
	}
	return *o.CompanyId
}

// GetCompanyIdOk returns a tuple with the CompanyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUserResponse200AllOfData) GetCompanyIdOk() (*int32, bool) {
	if o == nil || IsNil(o.CompanyId) {
		return nil, false
	}
	return o.CompanyId, true
}

// HasCompanyId returns a boolean if a field has been set.
func (o *GetCurrentUserResponse200AllOfData) HasCompanyId() bool {
	if o != nil && !IsNil(o.CompanyId) {
		return true
	}

	return false
}

// SetCompanyId gets a reference to the given int32 and assigns it to the CompanyId field.
func (o *GetCurrentUserResponse200AllOfData) SetCompanyId(v int32) {
	o.CompanyId = &v
}

// GetCompanyName returns the CompanyName field value if set, zero value otherwise.
func (o *GetCurrentUserResponse200AllOfData) GetCompanyName() string {
	if o == nil || IsNil(o.CompanyName) {
		var ret string
		return ret
	}
	return *o.CompanyName
}

// GetCompanyNameOk returns a tuple with the CompanyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUserResponse200AllOfData) GetCompanyNameOk() (*string, bool) {
	if o == nil || IsNil(o.CompanyName) {
		return nil, false
	}
	return o.CompanyName, true
}

// HasCompanyName returns a boolean if a field has been set.
func (o *GetCurrentUserResponse200AllOfData) HasCompanyName() bool {
	if o != nil && !IsNil(o.CompanyName) {
		return true
	}

	return false
}

// SetCompanyName gets a reference to the given string and assigns it to the CompanyName field.
func (o *GetCurrentUserResponse200AllOfData) SetCompanyName(v string) {
	o.CompanyName = &v
}

// GetCompanyDomain returns the CompanyDomain field value if set, zero value otherwise.
func (o *GetCurrentUserResponse200AllOfData) GetCompanyDomain() string {
	if o == nil || IsNil(o.CompanyDomain) {
		var ret string
		return ret
	}
	return *o.CompanyDomain
}

// GetCompanyDomainOk returns a tuple with the CompanyDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUserResponse200AllOfData) GetCompanyDomainOk() (*string, bool) {
	if o == nil || IsNil(o.CompanyDomain) {
		return nil, false
	}
	return o.CompanyDomain, true
}

// HasCompanyDomain returns a boolean if a field has been set.
func (o *GetCurrentUserResponse200AllOfData) HasCompanyDomain() bool {
	if o != nil && !IsNil(o.CompanyDomain) {
		return true
	}

	return false
}

// SetCompanyDomain gets a reference to the given string and assigns it to the CompanyDomain field.
func (o *GetCurrentUserResponse200AllOfData) SetCompanyDomain(v string) {
	o.CompanyDomain = &v
}

// GetCompanyCountry returns the CompanyCountry field value if set, zero value otherwise.
func (o *GetCurrentUserResponse200AllOfData) GetCompanyCountry() string {
	if o == nil || IsNil(o.CompanyCountry) {
		var ret string
		return ret
	}
	return *o.CompanyCountry
}

// GetCompanyCountryOk returns a tuple with the CompanyCountry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUserResponse200AllOfData) GetCompanyCountryOk() (*string, bool) {
	if o == nil || IsNil(o.CompanyCountry) {
		return nil, false
	}
	return o.CompanyCountry, true
}

// HasCompanyCountry returns a boolean if a field has been set.
func (o *GetCurrentUserResponse200AllOfData) HasCompanyCountry() bool {
	if o != nil && !IsNil(o.CompanyCountry) {
		return true
	}

	return false
}

// SetCompanyCountry gets a reference to the given string and assigns it to the CompanyCountry field.
func (o *GetCurrentUserResponse200AllOfData) SetCompanyCountry(v string) {
	o.CompanyCountry = &v
}

// GetCompanyIndustry returns the CompanyIndustry field value if set, zero value otherwise.
func (o *GetCurrentUserResponse200AllOfData) GetCompanyIndustry() string {
	if o == nil || IsNil(o.CompanyIndustry) {
		var ret string
		return ret
	}
	return *o.CompanyIndustry
}

// GetCompanyIndustryOk returns a tuple with the CompanyIndustry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUserResponse200AllOfData) GetCompanyIndustryOk() (*string, bool) {
	if o == nil || IsNil(o.CompanyIndustry) {
		return nil, false
	}
	return o.CompanyIndustry, true
}

// HasCompanyIndustry returns a boolean if a field has been set.
func (o *GetCurrentUserResponse200AllOfData) HasCompanyIndustry() bool {
	if o != nil && !IsNil(o.CompanyIndustry) {
		return true
	}

	return false
}

// SetCompanyIndustry gets a reference to the given string and assigns it to the CompanyIndustry field.
func (o *GetCurrentUserResponse200AllOfData) SetCompanyIndustry(v string) {
	o.CompanyIndustry = &v
}

// GetLanguage returns the Language field value if set, zero value otherwise.
func (o *GetCurrentUserResponse200AllOfData) GetLanguage() GetCurrentUserResponse200AllOfDataAllOfLanguage {
	if o == nil || IsNil(o.Language) {
		var ret GetCurrentUserResponse200AllOfDataAllOfLanguage
		return ret
	}
	return *o.Language
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentUserResponse200AllOfData) GetLanguageOk() (*GetCurrentUserResponse200AllOfDataAllOfLanguage, bool) {
	if o == nil || IsNil(o.Language) {
		return nil, false
	}
	return o.Language, true
}

// HasLanguage returns a boolean if a field has been set.
func (o *GetCurrentUserResponse200AllOfData) HasLanguage() bool {
	if o != nil && !IsNil(o.Language) {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given GetCurrentUserResponse200AllOfDataAllOfLanguage and assigns it to the Language field.
func (o *GetCurrentUserResponse200AllOfData) SetLanguage(v GetCurrentUserResponse200AllOfDataAllOfLanguage) {
	o.Language = &v
}

func (o GetCurrentUserResponse200AllOfData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCurrentUserResponse200AllOfData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.DefaultCurrency) {
		toSerialize["default_currency"] = o.DefaultCurrency
	}
	if !IsNil(o.Locale) {
		toSerialize["locale"] = o.Locale
	}
	if !IsNil(o.Lang) {
		toSerialize["lang"] = o.Lang
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if o.Phone.IsSet() {
		toSerialize["phone"] = o.Phone.Get()
	}
	if !IsNil(o.Activated) {
		toSerialize["activated"] = o.Activated
	}
	if !IsNil(o.LastLogin) {
		toSerialize["last_login"] = o.LastLogin
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if o.Modified.IsSet() {
		toSerialize["modified"] = o.Modified.Get()
	}
	if !IsNil(o.HasCreatedCompany) {
		toSerialize["has_created_company"] = o.HasCreatedCompany
	}
	if !IsNil(o.Access) {
		toSerialize["access"] = o.Access
	}
	if !IsNil(o.ActiveFlag) {
		toSerialize["active_flag"] = o.ActiveFlag
	}
	if !IsNil(o.TimezoneName) {
		toSerialize["timezone_name"] = o.TimezoneName
	}
	if !IsNil(o.TimezoneOffset) {
		toSerialize["timezone_offset"] = o.TimezoneOffset
	}
	if !IsNil(o.RoleId) {
		toSerialize["role_id"] = o.RoleId
	}
	if o.IconUrl.IsSet() {
		toSerialize["icon_url"] = o.IconUrl.Get()
	}
	if !IsNil(o.IsYou) {
		toSerialize["is_you"] = o.IsYou
	}
	if !IsNil(o.IsDeleted) {
		toSerialize["is_deleted"] = o.IsDeleted
	}
	if !IsNil(o.CompanyId) {
		toSerialize["company_id"] = o.CompanyId
	}
	if !IsNil(o.CompanyName) {
		toSerialize["company_name"] = o.CompanyName
	}
	if !IsNil(o.CompanyDomain) {
		toSerialize["company_domain"] = o.CompanyDomain
	}
	if !IsNil(o.CompanyCountry) {
		toSerialize["company_country"] = o.CompanyCountry
	}
	if !IsNil(o.CompanyIndustry) {
		toSerialize["company_industry"] = o.CompanyIndustry
	}
	if !IsNil(o.Language) {
		toSerialize["language"] = o.Language
	}
	return toSerialize, nil
}

type NullableGetCurrentUserResponse200AllOfData struct {
	value *GetCurrentUserResponse200AllOfData
	isSet bool
}

func (v NullableGetCurrentUserResponse200AllOfData) Get() *GetCurrentUserResponse200AllOfData {
	return v.value
}

func (v *NullableGetCurrentUserResponse200AllOfData) Set(val *GetCurrentUserResponse200AllOfData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCurrentUserResponse200AllOfData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCurrentUserResponse200AllOfData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCurrentUserResponse200AllOfData(val *GetCurrentUserResponse200AllOfData) *NullableGetCurrentUserResponse200AllOfData {
	return &NullableGetCurrentUserResponse200AllOfData{value: val, isSet: true}
}

func (v NullableGetCurrentUserResponse200AllOfData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCurrentUserResponse200AllOfData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


