/*
Pipedrive API v1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetNotesResponse200 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetNotesResponse200{}

// GetNotesResponse200 struct for GetNotesResponse200
type GetNotesResponse200 struct {
	// If the request was successful or not
	Success *bool `json:"success,omitempty"`
	// The array of notes
	Data []GetNotesResponse200DataInner `json:"data,omitempty"`
	AdditionalData *GetNotesResponse200AdditionalData `json:"additional_data,omitempty"`
}

// NewGetNotesResponse200 instantiates a new GetNotesResponse200 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNotesResponse200() *GetNotesResponse200 {
	this := GetNotesResponse200{}
	return &this
}

// NewGetNotesResponse200WithDefaults instantiates a new GetNotesResponse200 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNotesResponse200WithDefaults() *GetNotesResponse200 {
	this := GetNotesResponse200{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetNotesResponse200) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNotesResponse200) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetNotesResponse200) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GetNotesResponse200) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetNotesResponse200) GetData() []GetNotesResponse200DataInner {
	if o == nil || IsNil(o.Data) {
		var ret []GetNotesResponse200DataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNotesResponse200) GetDataOk() ([]GetNotesResponse200DataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetNotesResponse200) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []GetNotesResponse200DataInner and assigns it to the Data field.
func (o *GetNotesResponse200) SetData(v []GetNotesResponse200DataInner) {
	o.Data = v
}

// GetAdditionalData returns the AdditionalData field value if set, zero value otherwise.
func (o *GetNotesResponse200) GetAdditionalData() GetNotesResponse200AdditionalData {
	if o == nil || IsNil(o.AdditionalData) {
		var ret GetNotesResponse200AdditionalData
		return ret
	}
	return *o.AdditionalData
}

// GetAdditionalDataOk returns a tuple with the AdditionalData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNotesResponse200) GetAdditionalDataOk() (*GetNotesResponse200AdditionalData, bool) {
	if o == nil || IsNil(o.AdditionalData) {
		return nil, false
	}
	return o.AdditionalData, true
}

// HasAdditionalData returns a boolean if a field has been set.
func (o *GetNotesResponse200) HasAdditionalData() bool {
	if o != nil && !IsNil(o.AdditionalData) {
		return true
	}

	return false
}

// SetAdditionalData gets a reference to the given GetNotesResponse200AdditionalData and assigns it to the AdditionalData field.
func (o *GetNotesResponse200) SetAdditionalData(v GetNotesResponse200AdditionalData) {
	o.AdditionalData = &v
}

func (o GetNotesResponse200) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetNotesResponse200) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.AdditionalData) {
		toSerialize["additional_data"] = o.AdditionalData
	}
	return toSerialize, nil
}

type NullableGetNotesResponse200 struct {
	value *GetNotesResponse200
	isSet bool
}

func (v NullableGetNotesResponse200) Get() *GetNotesResponse200 {
	return v.value
}

func (v *NullableGetNotesResponse200) Set(val *GetNotesResponse200) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNotesResponse200) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNotesResponse200) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNotesResponse200(val *GetNotesResponse200) *NullableGetNotesResponse200 {
	return &NullableGetNotesResponse200{value: val, isSet: true}
}

func (v NullableGetNotesResponse200) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNotesResponse200) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


